name: Commit PR Patch to Repo

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number to commit
        required: true
      artifact_name:
        description: Artifact name (default pr-<PR>-patch)
        required: false

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name || format('pr-{0}-patch', inputs.pr_number) }}
          path: pr-reviews

      - name: Commit patch file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pr-reviews/
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(pr-reviews): add patch for PR #${{ inputs.pr_number }}"
          git push