name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run schema validation tests
      run: node --test test/schema.test.js
      
    - name: Validate example files exist and are valid JSON
      run: |
        echo "Checking example files..."
        ERROR_COUNT=0
        find examples -name "*.json" -o -name "*.jsonld" | while read file; do
          echo "Validating JSON syntax in $file"
          if ! node -e "JSON.parse(require('fs').readFileSync('$file', 'utf8'))" 2>/dev/null; then
            echo "❌ ERROR: Invalid JSON syntax in $file"
            ERROR_COUNT=$((ERROR_COUNT + 1))
          else
            echo "✅ Valid JSON: $file"
          fi
        done
        if [ $ERROR_COUNT -gt 0 ]; then
          echo "Found $ERROR_COUNT files with JSON syntax errors"
          echo "Note: These may be intentional (e.g., files with comments for documentation)"
        fi
        echo "JSON validation check completed"